### ISSUE TITLE
Rules and regulations : DK

### ISSUE THREAD

**Issue by OwenBrotherwood** [TheThingsNetworkDenmark/TheThingsNetworkDenmark#1]
The normal template for a country refers to rules and regulations that are different from country to country.

Issue regards a short and correct description of the rules and regulations in denmark at this time with a continual issue as to how to ensure compliance to rules and regulations as time goes by.

![image](https://cloud.githubusercontent.com/assets/866122/23329539/091e2418-fb3b-11e6-99af-96a03291c9b5.png)

**Comment by OwenBrotherwood** [comment]
Rish is investigating the "READ MORE" link that goes to a wiki without real contect for the use of Rules and Regulations

**Comment by OwenBrotherwood** [comment]
This issue is moved to the next thing milestone as the basis of success has not been found as yet

**Comment by sebastianbuettrich** [comment]
Denmark is in all respects part of ITU Region 1, with all the rules that come with that - as far as ISM 868 is concerned.

**Comment by OwenBrotherwood** [comment]
https://en.wikipedia.org/wiki/International_Telecommunication_Union
- ITU International Telecommunication Union

https://en.wikipedia.org/wiki/ITU_Region
- ITU Region 1

https://en.wikipedia.org/wiki/European_Conference_of_Postal_and_Telecommunications_Administrations
- CEPT European Conference of Postal and Telecommunications Administrations

https://en.wikipedia.org/wiki/ISM_band
- ISM Industrial, Scientific and Medical Band
  - https://en.wikipedia.org/wiki/ISM_band#Frequency_allocation
    - https://en.wikipedia.org/wiki/ISM_band#Non-ISM_uses

https://en.wikipedia.org/wiki/Category:ITU_Radio_Regulations
- bullets

---

https://www.thethingsnetwork.org/wiki/LoRaWAN/Home
https://www.thethingsnetwork.org/wiki/LoRaWAN/Frequencies WIP ???

**Comment by sebastianbuettrich** [comment]
In Denmark, Frequencies are regulated by Frekvensstyrelsen under Energistyrelsen , but there s nothing specific here - it s all standard ITU/ETSI stuff, same as rest of europe.
https://ens.dk/ansvarsomraader/frekvenser
fancy maps:
http://frekvens.erhvervsstyrelsen.dk/

**Comment by OwenBrotherwood** [comment]
https://ens.dk/ansvarsomraader/frekvenser
- I haven't found anything that looks like TTN freq and any real "OK to use" from the danish authorities
  - ie a clear indication that can be shown to "others" that "everything is OK"

Working thru the paragrafs ...

https://ens.dk/ansvarsomraader/frekvenser/skal-du-anvende-frekvenser

![image](https://cloud.githubusercontent.com/assets/866122/23472966/d634ba90-feae-11e6-9c05-9ee73c26bee8.png)

https://www.retsinformation.dk/Forms/R0710.aspx?id=184814

https://www.retsinformation.dk/Forms/R0710.aspx?id=184814#id295013f4-03f2-4340-b1ad-e9ed71fd301c
- Bilag 5 Radiofrekvenser til andre tjenester, som må anvendes uden tilladelse, jf. § 5 
  - The Bilag 5, $5 thingy may be the text that contains the danish ok ("uden forbehold" as is sometimes used ind denmark or more correct, "med forbehold": one has to live in denmark to get this comment)

**Comment by sebastianbuettrich** [comment]
TTN uses ISM 868 - and is listed in https://www.retsinformation.dk/Forms/R0710.aspx?id=184814#id295013f4-03f2-4340-b1ad-e9ed71fd301c

summary - no worries.

**Comment by OwenBrotherwood** [comment]
I make a summary that is the "rules and regulations" that are from the main page of country denmark

I will ask for that the standard icon "Read More" doesn't just land in some generic wiki

![image](https://cloud.githubusercontent.com/assets/866122/23499320/ef94711a-ff2b-11e6-9202-d10541f51ba5.png)

https://thethingsnetwork.slack.com/files/owen_brotherwood/F4CFJFUFM/pasted_image_at_2017_03_02_09_42_am.png

**Comment by OwenBrotherwood** [comment]
Danish text with laws and regulations is now found
